version: "3.3"
services:
  mongo:
    image: mongo:latest
    container_name: "mongo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --bind_ip_all --smallfiles --logpath=/dev/null
  smidiv-api:
    build: ./smidiv-api
    container_name: "smidiv-api"
    environment:
      - API_URL=smidiv-api
      - MONGO_URL=mongo
    ports:
      - "10010:10010"
  smidiv-react:
    build: ./smidiv-react
    container_name: "smidiv-react"
    environment:
      - API_URL=smidiv-api
    ports:
      - "80:3000"
